# Generated by Django 3.2.13 on 2022-05-04 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('new client', 'New Client'), ('active client', 'Active Client'), ('ex-client', 'Ex-Client'), ('lead', 'Lead'), ('referral', 'Referral'), ('guest', 'Guest'), ('cross & upgrade', 'Cross & Upgrade')], max_length=255)),
                ('meeting_type', models.CharField(choices=[('spontaneous', 'Spontaneous'), ('comeback', 'Comeback')], max_length=255)),
                ('category', models.CharField(choices=[('comeback', 'Comeback'), ('prospect', 'Prospect')], max_length=255)),
                ('accepted', models.BooleanField()),
                ('referrals', models.PositiveIntegerField(default=0)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
            options={
                'permissions': (('access_offer', 'Access offer'),),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=18)),
                ('slug', models.SlugField(unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='OfferedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('number_of_months', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.product')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('month', models.DateField()),
                ('working_days', models.PositiveIntegerField(default=23, help_text='Number of working days')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.PositiveIntegerField(default=0, help_text='time in seconds')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('miss new', 'Miss New'), ('miss active', 'Miss Active'), ('miss ex client', 'Miss Ex Client'), ('miss lead', 'Miss Lead'), ('miss referral', 'Miss Referral'), ('miss guest', 'Miss Guest'), ('ex client', 'Ex Client'), ('active client', 'Active Client'), ('lead', 'Lead'), ('referral', 'Referral'), ('guest', 'Guest'), ('info', 'Info'), ('relation', 'Relation'), ('other', 'Other')], max_length=255)),
                ('action', models.CharField(choices=[('missed calls', 'Missed Calls'), ('calls', 'Calls'), ('e-mails', 'E-Mails'), ('message', 'Message'), ('booked meetings', 'Booked Meetings'), ('no show', 'No Show'), ('extra referrals', 'Extra Referrals')], max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club')),
            ],
            options={
                'permissions': (('access_action', 'Access action'),),
            },
        ),
    ]
