# Generated by Django 3.2.13 on 2022-04-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='working_days',
            field=models.PositiveIntegerField(default=23, help_text='Number of working days'),
        ),
        migrations.AlterField(
            model_name='action',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='action',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='time in seconds'),
        ),
    ]
