# Generated by Django 3.2.13 on 2022-05-19 05:53

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0003_workinghour'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghour',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='offereditem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='club',
        ),
        migrations.RemoveField(
            model_name='product',
            name='value',
        ),
        migrations.AddField(
            model_name='offereditem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='workinghour',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='workinghour',
            unique_together={('agent', 'date')},
        ),
    ]
