# Generated by Django 3.2.13 on 2022-04-29 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_alter_offer_offered_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offered_items',
        ),
        migrations.AddField(
            model_name='offereditem',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.offer'),
        ),
        migrations.AlterField(
            model_name='offereditem',
            name='number_of_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
