# Generated by Django 3.2.13 on 2022-05-02 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20220429_2352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'permissions': (('access_offer', 'Access offer'),)},
        ),
    ]
