# Generated by Django 3.2.13 on 2022-07-08 10:52

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0004_auto_20220519_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-date'], 'permissions': (('access_action', 'Access action'),)},
        ),
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-month']},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-date'], 'permissions': (('access_offer', 'Access offer'),)},
        ),
        migrations.AlterModelOptions(
            name='workinghour',
            options={'ordering': ['-date'], 'permissions': (('access_working_hour', 'Access working hour'),)},
        ),
        migrations.AlterField(
            model_name='offer',
            name='client_type',
            field=models.CharField(choices=[('new client', 'New Client'), ('active client', 'Active Client'), ('ex-client', 'Ex-Client'), ('lead', 'Lead'), ('referral', 'Referral'), ('guest', 'Guest'), ('cross upgrade', 'Cross & Upgrade')], max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='offer',
            name='meeting_type',
            field=models.CharField(choices=[('spontaneous', 'Spontaneous'), ('booked', 'Booked')], max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('agent', 'month')},
        ),
    ]
