# Generated by Django 3.2.13 on 2022-07-12 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0005_auto_20220708_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
    ]
