# Generated by Django 3.2.13 on 2022-07-08 14:44

from django.db import migrations, models
import fitgenius.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220504_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=fitgenius.users.models.get_user_image_dir),
        ),
    ]
