# Generated by Django 3.2.13 on 2022-07-12 09:53

from django.db import migrations, models
import django.db.models.deletion
import fitgenius.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_club_manager'),
        ('users', '0003_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.club'),
        ),
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=fitgenius.users.models.get_user_image_dir, verbose_name='Avatar'),
        ),
    ]
